---
title: "Buffer overlay experiment"
author: "Rebecca Folmer Schade"
date: "28 maj 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..")
```

# Loading packages 

```{r}
pacman::p_load(pacman, tidyverse, dplyr, sf, leaflet, stringr, htmlwidgets, raster, shiny)
```

# Loading data 

```{r}
# load data
test_data <- st_read("data/EEA_points.shp")
```

# Checking out dbscan

```{r}
install.packages("dbscan")

# Load the package and use the numeric variables in the iris dataset
library(dbscan)

data("iris")
x <- as.matrix(iris[, 1:4])

# Run dbscan
db <- dbscan(x, eps = .4, minPts = 4)
db$cluster

# Visualize results 
pairs(x, col = db$cluster + 1L)

# Calculate and visualize local outlier factor 
lof <- lof(x, k = 4)
pairs(x, cex = lof)

# Run optics 
opt <- optics(x, eps = 1, minPts = 4)
opt

# Extract DBSCAN-like clustering from OPTICS and create a reachability plot (extracted DBSCAN clusters at eps_cl=.4 are colored)
opt <- extractDBSCAN(opt, eps_cl = .4)
plot(opt)

# Extract a hierarchical clustering using the Xi method (captures clusters of varying density)
opt <- extractXi(opt, xi = .05)
opt
plot(opt)

# Run HDBSCAN (captures stable clusters)
hdb <- hdbscan(x, minPts = 4)
hdb

# Visualize as a simplified tree
plot(hdb, show_flat = T)

# See how well each point corresponds to the clusters found by the model used
colors <- mapply(function(col, i) adjustcolor(col, alpha.f = hdb$membership_prob[i]), 
                   palette()[hdb$cluster+1], seq_along(hdb$cluster))
  plot(x, col=colors, pch=20)
```

# Trying to use dbscan with a spatial object 

```{r}
# Checking data 
head(test_data)

# re-projecting data because I am a dum dum 
test_transform <- st_transform(test_data, crs = 3035)
head(test_transform)
# > Perfect! The unit of this is in metres! 
plot(st_geometry(test_transform))

# Making a coordinate dataframe with lat and long in separate columns
test_transform_df <- st_coordinates(test_transform)
colnames(test_transform_df) <- c('northing', 'easting')

# Making clusters
# > Units should be in metres, so this should be 5 km radius
res <-  dbscan(test_transform_df, eps = 5000, minPts = 3)
res

# Giving datapoints cluster ID's 
test_transform$dbscan_id <- res$cluster

# Making a dataset of clusters
clusters <- test_transform %>%
  filter(dbscan_id >= 1) %>% 
  group_by(dbscan_id) %>% 
  summarize(geometry = st_union(geometry), nr_points = n())

# Computing the convex hull 
cluster_hull <- st_convex_hull(clusters)

# Ploting the points together with the hull
plot(st_geometry(test_transform));plot(cluster_hull, add = TRUE) 
# > This is not a very good visualization, but I think I get it. 

#=====> Maybe it will help if I try to visualize it in leaflet 
# Transforming to web mercator 
crs_needed <- "+proj=longlat +datum=WGS84"
test_web <- st_transform(test_transform, crs = crs_needed)
hull_web<- st_transform(cluster_hull, crs = crs_needed)

# Leaflet
#### map it
test_map_1 <- leaflet() %>%
  addTiles() %>% 
  addControl("Queer Travel Map", position = "topleft", className="map-title") %>% 
  addProviderTiles("Esri.WorldTopoMap", group = "Topographic") %>%
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  
  # first overlay:
  addCircleMarkers(data = test_web,
                   opacity = 0.5, color = "black", stroke = TRUE,
                   fillOpacity = 0.5, weight=2, fillColor = "purple",
                   popup = paste0("Name: ", test_web$name,
                                  "<br> Type: ", test_web$amenity,
                                  "<br> Website: ", test_web$website,
                                  "<br> Opening hours: ", test_web$opnng_h),
                   group = "Safe spaces",
                   clusterOptions = markerClusterOptions()) %>%
  
  # extra test overlay - markers:
  addCircleMarkers(data = cities_sf3035,
                   opacity = 0.5, color = "black", stroke = TRUE,
                   fillOpacity = 0.5, weight=2, fillColor = "purple", 
                   group = "More safe spaces",
                   clusterOptions = markerClusterOptions()) %>%
  
  # add overlay - e.g. polygon like here:
  addPolygons(data = hull_web,
              fill = T, weight = 2, color = "purple",
              popup = paste0("Name: ", "gayboorhood-name"), 
              group = "Safe space density") %>%
  
  # add heatmap
  #addRasterImage(Aster) %>% 
  # it doesn't recognize the addHeatmap() function, so it's probably in a package
  #addHeatmap(map, lng = NULL, lat = NULL, intensity = NULL,
  #layerId = NULL, group = NULL, minOpacity = 0.05, max = 1,
  #radius = 25, blur = 15, gradient = NULL, cellSize = NULL,
  #data = leaflet::getMapData(map)) %>% 

  # add control things
  addLayersControl(
    baseGroups = c("Topographic","Aerial"),
    overlayGroups = c("Safe spaces", "More safe spaces", "Safe space density"),
    options = layersControlOptions(collapsed = T))
  
test_map_1

# > HA! That worked! Take that!
# > I have not managed to change the colors depending on how many points a cljuster contains, but I have managed to create a nr_points variable!

```

# Understanding leaflet

```{r}
# Creating an unrelated map
popup = c("Robin", "Jakub", "Jannes")

leaflet() %>%
  addProviderTiles("Esri.WorldPhysical") %>% 
 #addProviderTiles("Esri.WorldImagery") %>% 
  addAwesomeMarkers(lng = c(-3, 23, 11),
                    lat = c(52, 53, 49), 
                    popup = popup)

# Changing crs 
crs_needed <- "+proj=longlat +datum=WGS84"
safespace_crs <- st_transform(test_data, crs = crs_needed)

# Trying for a simple plot with the datapoints
test_map <- leaflet() %>%
  addTiles() %>% # insert this in the parenthesis: attribution = 'By Rebecca Schade and Sophia Karlson'
  addControl("Queer Travel Map", position = "topleft", className="map-title") %>% # make this bigger!
  addProviderTiles("Esri.WorldPhysical") %>%
  addCircleMarkers(data = safespace_crs,
                   opacity = 0.5, color = "black", stroke = TRUE,
                   fillOpacity = 0.5, weight=2, fillColor = "purple",
                   popup = paste0("Name: ", test_data$name,
                                  "<br> Type: ", test_data$amenity,
                                  "<br> Website: ", test_data$website,
                                  "<br> Opening hours: ", test_data$opnng_h), #,
                                  # if we had the data, these could be added as well:
                                  #"<br> Address: ", test_data$address),
                                  # who it is for (only men, everyone etc)
                   group = "Safe spaces",#if we don't want the user to be able to not see all the safe spaces, cut this
                  #) %>%
                   clusterOptions = markerClusterOptions()) %>%
  
  # add density overlay here
  
  # do the control stuff
  addLayersControl(
    baseGroups = c("Topographic","Aerial"),
    overlayGroups = c("Safe spaces", "Safe space density"), # there is no safe-space density yet
    options = layersControlOptions(collapsed = T))
  
test_map

# Trying to add a buffer layers

#Make buffer of 5 km. Check the units of your object to correctly assign value to dist
safe_space_1km<- st_buffer(st_geometry(safespace_crs), dist = 1) 
?st_buffer
st_crs(test_data)
plot(safe_space_1km)
class(safe_space_1km)
st_crs(safespace_crs, asText = TRUE) == st_crs(safe_space_1km, asText = TRUE)

#### map it
test_map_1 <- leaflet() %>%
  addTiles() %>% 
  addControl("Queer Travel Map", position = "topleft", className="map-title") %>% 
  addProviderTiles("Esri.WorldTopoMap", group = "Topographic") %>%
  addProviderTiles("Esri.WorldImagery", group = "Aerial") %>%
  
  # first overlay:
  addCircleMarkers(data = safespace_crs,
                   opacity = 0.5, color = "black", stroke = TRUE,
                   fillOpacity = 0.5, weight=2, fillColor = "purple",
                   popup = paste0("Name: ", test_data$name,
                                  "<br> Type: ", test_data$amenity,
                                  "<br> Website: ", test_data$website,
                                  "<br> Opening hours: ", test_data$opnng_h),
                   group = "Safe spaces",
                   clusterOptions = markerClusterOptions()) %>%
  
  # extra test overlay - markers:
  addCircleMarkers(data = cities_sf3035,
                   opacity = 0.5, color = "black", stroke = TRUE,
                   fillOpacity = 0.5, weight=2, fillColor = "purple", 
                   group = "More safe spaces",
                   clusterOptions = markerClusterOptions()) %>%
  
  # add overlay - e.g. polygon like here:
  addPolygons(data = safe_space_1km,
              fill = T, weight = 2, color = "purple",
              popup = paste0("Name: ", "gayboorhood-name"), 
              group = "Safe space density") %>%
  
  # add heatmap
  #addRasterImage(Aster) %>% 
  # it doesn't recognize the addHeatmap() function, so it's probably in a package
  #addHeatmap(map, lng = NULL, lat = NULL, intensity = NULL,
  #layerId = NULL, group = NULL, minOpacity = 0.05, max = 1,
  #radius = 25, blur = 15, gradient = NULL, cellSize = NULL,
  #data = leaflet::getMapData(map)) %>% 

  # add control things
  addLayersControl(
    baseGroups = c("Topographic","Aerial"),
    overlayGroups = c("Safe spaces", "More safe spaces", "Safe space density"),
    options = layersControlOptions(collapsed = T))
  
test_map_1
```