---
title: "Cluster analysis"
author: "Rebecca Folmer Schade & Sophia Kleist Karlson"
date: "2021-06-02 updated "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..")
```

## Loading packages

```{r, , results='hide', warning=FALSE, error=FALSE, message=FALSE}
# Quick install/load of all used packages if needed 
# install.packages("pacman")
# pacman::p_load(pacman, sf, raster, tidyverse, spatstat, maptools)
library(sf)
library(raster)
library(tidyverse)
library(spatstat)
library(maptools)
```

# Loading data 

```{r, results='hide', warning=FALSE, message=FALSE, error=FALSE}
# load data
EEA_points <- st_read("data/EEA_points.shp")
```

### Converting to ppp

```{r}
#=====> Creating a convex hull to use as a window for analysis 
# Converting points to a single multi-point
multi_points <- st_union(EEA_points)

# Computing the convex hull 
points_hull <- st_convex_hull(multi_points)

# Ploting the points together with the hull
plot(points_hull, col = "red"); plot(st_geometry(multi_points), add = TRUE)

# Turning kaz_mounds into a ppp object
points_pre_p <- as.ppp(EEA_points)

# Turning the convex hull into a window
points_window <- as.owin(points_hull)

# Adding the window to the ppp object 
points_p <-ppp(points_pre_p$x, points_pre_p$y, window=points_window)

# plotting a square window against the convex hull widow to compare.
plot(points_pre_p);plot(points_p)

```

### Applying K function 

```{r}
# Estimating the K-function with the correction argument as "border" for edge correction.  
points_k <- Kest(points_p, correction = "Ripley")

# Plotting the K-function
plot(points_k)

# Computing envelopes of K 
k_env <- envelope(points_p, Kest, correction = "Ripley")

# Plotting the K-function with the envelope and the ". - pi * r ^ 2 ~ r" formula to center the funtion of the expected K-function for a random poisson distribution for easier comparison. 
plot(k_env, . - pi * r ^ 2 ~ r)

# plotting K normally because this is easier for me to understand in this case
plot(k_env)
```

